# Generated by Django 5.1.6 on 2026-03-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('paid', 'Pagado'), ('issued', 'Emitido'), ('cancelled', 'Cancelado')], default='paid', max_length=20, verbose_name='Estado')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
