# Generated by Django 5.1.6 on 2026-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='Número de vuelo')),
                ('airline', models.CharField(max_length=100, verbose_name='Aerolínea')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('departure_time', models.DateTimeField(verbose_name='Fecha y hora de salida')),
                ('arrival_time', models.DateTimeField(verbose_name='Fecha y hora de llegada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('seats_available', models.PositiveIntegerField(verbose_name='Asientos disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['departure_time'],
            },
        ),
    ]
